export const componentMap = {
  button: ['Button'],
  icon: ['Icon'],
  link: ['Link'],
  grid: ['Row', 'Col'],
  layout: ['Aside', 'Content', 'Footer', 'Header', 'Layout'],
  divider: ['Divider'],
  space: ['Space'],
  descriptions: ['Descriptions', 'DescriptionsItem'],
  affix: ['Affix'],
  anchor: ['Anchor', 'AnchorItem', 'AnchorTarget'],
  breadcrumb: ['Breadcrumb', 'BreadcrumbItem'],
  dropdown: ['Dropdown', 'DropdownItem', 'DropdownMenu'],
  menu: ['HeadMenu', 'Menu', 'MenuGroup', 'MenuItem', 'Submenu'],
  pagination: ['Pagination', 'PaginationMini'],
  steps: ['StepItem', 'Steps'],
  tabs: ['TabPanel', 'Tabs'],
  'sticky-tool': ['StickyItem', 'StickyTool'],
  'back-top': ['BackTop'],
  'auto-complete': ['AutoComplete', 'HighlightOption'],
  cascader: ['Cascader', 'CascaderPanel'],
  checkbox: ['Checkbox', 'CheckboxGroup'],
  'date-picker': ['DatePicker', 'DatePickerPanel', 'DateRangePicker', 'DateRangePickerPanel'],
  form: ['Form', 'FormItem'],
  'input-adornment': ['InputAdornment'],
  input: ['Input', 'InputGroup'],
  'input-number': ['InputNumber'],
  radio: ['Radio', 'RadioButton', 'RadioGroup'],
  select: ['Option', 'OptionGroup', 'Select'],
  slider: ['Slider', 'SliderButton'],
  switch: ['Switch'],
  'tag-input': ['TagInput'],
  'select-input': ['SelectInput'],
  textarea: ['Textarea'],
  transfer: ['Transfer'],
  'time-picker': ['TimePicker', 'TimePickerPanel', 'TimeRangePicker'],
  'tree-select': ['TreeSelect'],
  'color-picker': ['ColorPicker', 'ColorPickerPanel'],
  'range-input': ['RangeInput', 'RangeInputPopup'],
  avatar: ['Avatar', 'AvatarGroup'],
  badge: ['Badge'],
  calendar: ['Calendar'],
  card: ['Card'],
  comment: ['Comment'],
  image: ['Image'],
  'image-viewer': ['ImageViewer'],
  list: ['List', 'ListItem', 'ListItemMeta'],
  progress: ['Progress'],
  skeleton: ['Skeleton'],
  statistic: ['Statistic'],
  swiper: ['Swiper', 'SwiperItem'],
  table: ['BaseTable', 'EnhancedTable', 'PrimaryTable', 'Table'],
  tag: ['CheckTag', 'CheckTagGroup', 'Tag'],
  timeline: ['Timeline', 'TimelineItem'],
  tooltip: ['Tooltip'],
  tree: ['Tree'],
  collapse: ['Collapse', 'CollapsePanel'],
  watermark: ['Watermark'],
  rate: ['Rate'],
  alert: ['Alert'],
  dialog: ['DialogPlugin', 'Dialog'],
  drawer: ['Drawer'],
  guide: ['Guide'],
  loading: ['LoadingPlugin', 'Loading'],
  message: ['MessagePlugin', 'Message'],
  notification: ['NotifyPlugin', 'Notification'],
  popconfirm: ['Popconfirm'],
  popup: ['Popup'],
  upload: ['Upload'],
  'config-provider': ['ConfigProvider'],
  empty: ['Empty'],
  typography: ['Typography', 'Text', 'Title', 'Paragraph'],
};
