/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * 该文件由脚本自动生成，如需修改请联系 PMC
 * This file generated by scripts of tdesign-api. `npm run api:docs Typography VueNext(PC) vitest,finalProject`
 * If you need to modify this file, contact PMC first please.
 */
