packages:
  - packages/**
  - internal/**
catalogs:
  bundle:
    '@babel/cli': ^7.22.9
    '@babel/core': ^7.22.9
    '@babel/helper-module-imports': ^7.22.9
    '@babel/plugin-transform-modules-commonjs': ^7.22.5
    '@babel/plugin-transform-object-assign': ^7.22.5
    '@babel/plugin-transform-runtime': ^7.22.9
    '@babel/preset-env': ^7.22.9
    '@rollup/plugin-babel': ^6.0.3
    '@rollup/plugin-commonjs': ^24.0.0
    '@rollup/plugin-json': ^6.0.0
    '@rollup/plugin-node-resolve': ^16.0.1
    '@rollup/plugin-replace': ^5.0.2
    '@rollup/plugin-typescript': ^12.1.2
    '@rollup/plugin-url': ^7.0.0
    '@vitejs/plugin-vue': ^5.2.1
    '@vitejs/plugin-vue-jsx': ^4.1.2
    '@vue/babel-plugin-jsx': ^1.4.0
    '@vue/compiler-sfc': ^3.3.4
    autoprefixer: ^10.4.14
    cross-env: ^7.0.3
    esbuild: ^0.14.54
    execa: ^8.0.1
    fs-extra: ^11.3.0
    glob: ^11.0.1
    less: ^4.1.3
    postcss: ^8.4.26
    rimraf: ^5.0.1
    rollup: ^2.79.1
    rollup-plugin-analyzer: ^4.0.0
    rollup-plugin-copy: ^3.4.0
    rollup-plugin-delete: ^2.0.0
    rollup-plugin-esbuild: ^4.10.3
    rollup-plugin-ignore-import: ^1.3.2
    rollup-plugin-multi-input: ^1.4.1
    rollup-plugin-postcss: ^4.0.2
    rollup-plugin-static-import: ^0.1.1
    rollup-plugin-styles: ^4.0.0
    rollup-plugin-terser: ^7.0.2
    rollup-plugin-vue: ^6.0.0
    tsdown: ^0.12.9
    tsx: ^4.19.2
    vite: ^6.2.0
    vite-plugin-pwa: ^0.21.2
    vite-plugin-tdoc: ^2.0.4
  deps:
    '@babel/runtime': ^7.22.6
    '@popperjs/core': ^2.11.8
    clipboard: ^2.0.11
    dayjs: ^1.11.10
    highlight.js: ^11.9.0
    lodash: ^4.17.21
    lodash-es: ^4.17.21
    marked: ^12.0.1
    mitt: ^3.0.1
    nprogress: ^0.2.0
    raf: ^3.4.1
    sortablejs: ^1.15.0
    tinycolor2: ^1.6.0
    validator: ^13.9.0
    vue: ^3.3.9
    vue-router: ^4.2.4
  docs:
    gray-matter: ^4.0.3
    marked-highlight: ^2.1.1
    prismjs: ^1.29.0
    semver: ^7.5.4
    workbox-precaching: ^6.6.0
  lint:
    '@commitlint/cli': ^16.3.0
    '@commitlint/config-conventional': ^15.0.0
    '@typescript-eslint/eslint-plugin': ^4.33.0
    '@typescript-eslint/parser': ^4.33.0
    '@vue/eslint-config-typescript': ^10.0.0
    '@vue/tsconfig': ^0.7.0
    cz-git: ^1.7.0
    czg: ^1.7.0
    eslint: ^7.32.0
    eslint-config-prettier: ^8.8.0
    eslint-plugin-import: ^2.27.5
    eslint-plugin-prettier: ^4.2.1
    eslint-plugin-vue: ^8.7.1
    husky: ^7.0.4
    lint-staged: ^13.2.3
    prettier: ^2.8.1
  tdesign:
    '@tdesign/site-components': ^0.17.0
    tdesign-icons-view: ^0.3.7
    tdesign-icons-vue-next: 0.4.0-alpha.2
    tdesign-publish-cli: ^0.0.12
    tdesign-theme-generator: ^1.1.8
  test:
    '@testing-library/dom': ^9.3.1
    '@vue/test-utils': ^2.4.1
    canvas: '^3.1.2'
    dom-parser: ^1.1.5
    mockdate: ^3.0.5
    msw: ^1.2.3
    vitest: ^3.2.4
    vitest-fetch-mock: ^0.4.5
  types:
    '@types/lodash-es': ^4.17.12
    '@types/node': ^22.5.1
    '@types/nprogress': ^0.2.3
    '@types/raf': ^3.4.0
    '@types/sortablejs': ^1.15.1
    '@types/tinycolor2': ^1.4.3
    '@types/validator': ^13.7.17
    typescript: ^5.7.3
    vue-tsc: ^2.2.4
