<template>
  <t-comment
    avatar="https://tdesign.gtimg.com/list-icon.png"
    author="评论作者名"
    datetime="今天16:38"
    content="评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容。"
  ></t-comment>
</template>
<script></script>