<template>
  <t-chat :clear-history="false" :reverse="false" layout="single">
    <t-chat-item
      avatar="https://tdesign.gtimg.com/site/avatar.jpg"
      name="自己"
      role="user"
      datetime="今天16:38"
      content="牛顿第一定律是否适用于所有参考系？"
      variant="text"
    ></t-chat-item>
    <t-chat-item
      avatar="https://tdesign.gtimg.com/site/chat-avatar.png"
      name="TDesignAI"
      role="assistant"
      datetime="今天16:38"
      content="牛顿第一定律并不适用于所有参考系，它只适用于惯性参考系。在质点不受外力作用时，能够判断出质点静止或作匀速直线运动的参考系一定是惯性参考系，因此只有在惯性参考系中牛顿第一定律才适用。"
      variant="text"
    ></t-chat-item>
    <t-divider>有头像有昵称</t-divider>
    <t-chat-item
      avatar="https://tdesign.gtimg.com/site/avatar.jpg"
      role="user"
      content="牛顿第一定律是否适用于所有参考系？"
      variant="text"
    ></t-chat-item>
    <t-chat-item
      avatar="https://tdesign.gtimg.com/site/chat-avatar.png"
      role="assistant"
      content="牛顿第一定律并不适用于所有参考系，它只适用于惯性参考系。在质点不受外力作用时，能够判断出质点静止或作匀速直线运动的参考系一定是惯性参考系，因此只有在惯性参考系中牛顿第一定律才适用。"
      variant="text"
    ></t-chat-item>
    <t-divider>有头像无昵称</t-divider>
    <t-chat-item
      name="自己"
      role="user"
      datetime="今天16:38"
      content="牛顿第一定律是否适用于所有参考系？"
      variant="text"
    ></t-chat-item>
    <t-chat-item
      name="自己"
      role="assistant"
      datetime="今天16:38"
      content="牛顿第一定律并不适用于所有参考系，它只适用于惯性参考系。在质点不受外力作用时，能够判断出质点静止或作匀速直线运动的参考系一定是惯性参考系，因此只有在惯性参考系中牛顿第一定律才适用。"
      variant="text"
    ></t-chat-item>
    <t-divider>无头像有昵称</t-divider>
    <t-chat-item role="user" content="牛顿第一定律是否适用于所有参考系？" variant="text"></t-chat-item>
    <t-chat-item
      role="assistant"
      content="牛顿第一定律并不适用于所有参考系，它只适用于惯性参考系。在质点不受外力作用时，能够判断出质点静止或作匀速直线运动的参考系一定是惯性参考系，因此只有在惯性参考系中牛顿第一定律才适用。"
      variant="text"
    ></t-chat-item>
    <t-divider>无头像无昵称</t-divider>
  </t-chat>
</template>
<script setup></script>
<style scoped></style>
