name: auto-changelog

on:
  pull_request:
    branches: [develop]
    types: [opened, edited]
  issue_comment:
    types: [edited]

jobs:
  changelog:
    if: ${{ github.event.pull_request || github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          packages: 'tdesign-vue-next,@tdesign-vue-next/chat'
