name: auto-changelog

on:
  pull_request:
    branches: [develop]
    types: [opened, edited]
  issue_comment:
    types: [edited]

jobs:
  extract-changelog:
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/flow-pilot-action@develop
        with:
          packages: 'tdesign-vue-next,@tdesign-vue-next/chat'

  stash-changelog:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: auto-changelog
        uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          packages: 'tdesign-vue-next,@tdesign-vue-next/chat'
