name: auto-changelog

on:
  pull_request_review:
    types: [submitted]  

  issue_comment:
    types: [edited]

jobs:
  changelog:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'trigger ci auto-changelog-callback'

  commit-changelog:
    if: github.event.issue.pull_request || github.event.review.state == 'approved' 
    runs-on: ubuntu-latest
    steps:
      - name: auto-changelog
        uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          packages: 'tdesign-vue-next,@tdesign-vue-next/chat'
