# force copy from tencent/tdesign
name: Issue Add Assigness

on:
  issues:
    types: [opened, reopened]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/cn/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issues
      - uses: 94dreamer/create-report@main
        with:
          wxhook: ${{ secrets.WX_HOOK_URL }}
          token: ${{ secrets.GITHUB_TOKEN  }}
          type: 'issue'