name: Pull Request Auto Link

on: 
  pull_request: 
    types: closed

jobs:
  AddLabel:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: timi137137/tdesign-pr-auto-link@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
