name: pr-spell-check
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check spelling
      uses: crate-ci/typos@master
    - name: Use custom config file
      uses: crate-ci/typos@master
      with: 
        files: ./file.txt
        config: ./spelling-ignore.toml