name: MAIN_PULL_REQUEST

on:
  pull_request:
    branches: [develop, main]
    # opened：当 PR 创建时触发
    # synchronize：当 PR 的源分支有新的提交时触发
    # reopened：当关闭的 PR 重新打开时触发
    types: [opened, synchronize, reopened]

jobs:
  call-test-build:
    uses: TDesignOteam/workflows/.github/workflows/reusable-unit-test.yml@main
    with:
      node-version-file: .node-version
      skip-site: true
      package-manager: pnpm
